name: 'luast'
description: 'Build standalone Lua binaries with cross-compilation support'
author: 'pgagnidze'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  output:
    description: 'Output binary name (default: package name from rockspec)'
    required: false
  rockspec:
    description: 'Path to rockspec file (default: auto-detect)'
    required: false
  targets:
    description: 'Space-separated list of targets (e.g., "linux-x86_64 linux-arm64 macos-arm64 windows-x86_64")'
    required: false
  lua-version:
    description: 'Lua version to use (default: 5.4.8)'
    required: false

outputs:
  binary:
    description: 'Path to the built binary (or first binary if multiple targets)'
    value: ${{ steps.build.outputs.binary }}

runs:
  using: 'composite'
  steps:
    - name: Cache luast dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/luast
        key: luast-${{ runner.os }}

    - name: Install Lua (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4 liblua5.4-dev

    - name: Install Lua (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install lua

    - name: Build binary
      id: build
      shell: bash
      run: |
        LUAST_SCRIPT="${{ github.action_path }}/luast"

        if [ -n "${{ inputs.lua-version }}" ]; then
          export LUA_VERSION="${{ inputs.lua-version }}"
        fi

        ARGS=""

        if [ -n "${{ inputs.rockspec }}" ]; then
          ARGS="$ARGS -r ${{ inputs.rockspec }}"
        fi

        if [ -n "${{ inputs.targets }}" ]; then
          for target in ${{ inputs.targets }}; do
            ARGS="$ARGS -t $target"
          done
        fi

        if [ -n "${{ inputs.output }}" ]; then
          ARGS="$ARGS ${{ inputs.output }}"
        fi

        "$LUAST_SCRIPT" $ARGS

        OUTPUT="${{ inputs.output }}"
        if [ -z "$OUTPUT" ]; then
          OUTPUT=$(ls *.rockspec 2>/dev/null | head -1 | sed 's/-.*$//' || echo "output")
        fi

        echo "binary=$OUTPUT" >> $GITHUB_OUTPUT
